name: Go

on: 
  push:
    tags:
    - '*'
  
jobs:
  build_release:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16

    - name: Build
      run: |
        CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o TMGS3Tools_linux .
        CGO_ENABLED=0 GOOS=darwin GOARCH=amd64 go build -o TMGS3Tools_mac .
        CGO_ENABLED=0 GOOS=windows GOARCH=amd64 go build -o TMGS3Tools.exe .
    - uses: ncipollo/release-action@v1
      with:
        artifacts: "TMGS3Tools_linux,TMGS3Tools_mac,TMGS3Tools.exe"
        bodyFile: ""
        token: ${{ secrets.RELEASE_GITHUB_TOKEN }}
